// Re-export the shared schema so existing intra-app imports keep working.
export {
  agentCheckpoints,
  appSettings,
  baselines,
  currentDefinition,
  currentDefinitionOf,
  DDL,
  draftPreviews,
  environments,
  folders,
  replayedDefinition,
  replayedTestId,
  runAssertions,
  runEvidence,
  runNetwork,
  runResults,
  runs,
  runSteps,
  schema,
  suiteRuns,
  suites,
  suiteTests,
  tests,
  testSchedules,
  testTags,
} from "@varys/db";
export type { Db, DbHandle, RunStatus } from "@varys/db";
